/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.util.Random;


/**
 *
 * @author ACER
 */
public class tictactoe extends javax.swing.JFrame {

    int turn = 2;
    int buttonused[] = {0,0,0,0,0,0,0,0,0};
    int p1[] = {0,0,0,0,0,0,0,0,0};
    int p2[] = {0,0,0,0,0,0,0,0,0};
    
    
    
    int p1()
    {
        if(p1[0]==1 && p1[1]==1 && p1[2]==1)
        {return 1;}
        if(p1[3]==1 && p1[4]==1 && p1[5]==1)
        {return 1;}
        if(p1[6]==1 && p1[7]==1 && p1[8]==1)
        {return 1;}
        if(p1[0]==1 && p1[3]==1 && p1[6]==1)
        {return 1;}
        if(p1[1]==1 && p1[4]==1 && p1[7]==1)
        {return 1;}
        if(p1[2]==1 && p1[5]==1 && p1[8]==1)
        {return 1;}
        if(p1[0]==1 && p1[4]==1 && p1[8]==1)
        {return 1;}
        if(p1[2]==1 && p1[4]==1 && p1[6]==1)
        {return 1;}
        return 0;
    }
    int p2()
    {
        if(p2[0]==1 && p2[1]==1 && p2[2]==1)
        {return 1;}
        if(p2[3]==1 && p2[4]==1 && p2[5]==1)
        {return 1;}
        if(p2[6]==1 && p2[7]==1 && p2[8]==1)
        {return 1;}
        if(p2[0]==1 && p2[3]==1 && p2[6]==1)
        {return 1;}
        if(p2[1]==1 && p2[4]==1 && p2[7]==1)
        {return 1;}
        if(p2[2]==1 && p2[5]==1 && p2[8]==1)
        {return 1;}
        if(p2[0]==1 && p2[4]==1 && p2[8]==1)
        {return 1;}
        if(p2[2]==1 && p2[4]==1 && p2[6]==1)
        {return 1;}
        return 0;
    }
    
    public tictactoe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        b1.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        reset.setText("Play Again");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIC TAC TOE");

        tf.setText("Result");
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if (buttonused[0] == 0)
        {
        if(turn%2==0)
        {
            turn++;
            b1.setText("X");
            buttonused[0] = 1;
            p1[0] = 1;
             int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        else
        {
            turn++;
            b1.setText("O");
            buttonused[0] = 1;
            p2[0] = 1;
             int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(buttonused [1]==0)
        {
         if(turn%2==0)
        {
            turn++;
            b2.setText("X");
            buttonused[1]=1;
            p1[1] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        else
        {
            turn++;
            b2.setText("O");
            p2[1] = 1;
            buttonused[1]=1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(buttonused[2]==0)
        {
         if(turn%2==0)
        {
            turn++;
            b3.setText("X");
            buttonused[2]=1;
            p1[2] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
            
        }
        else
        {
            turn++;
            b3.setText("O");
            p2[2] = 1;
            buttonused[2]=1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(buttonused[3]==0)
        {
         if(turn%2==0)
        {
            turn++;
            b4.setText("X");
            buttonused[3]=1;
            p1[3] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}            
        }
        else
        {
            turn++;
            b4.setText("O");
            buttonused[3]=1;
            p2[3] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if(buttonused[4]==0)
        {
         if(turn%2==0)
        {
            turn++;
            buttonused[4]=1;
            b5.setText("X");
            p1[4] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        else
        {
            turn++;
            b5.setText("O");
            buttonused[4]=1;
            p2[4] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}            
        }
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if(buttonused[5]==0)
        {
        if(turn%2==0)
        {
            turn++;
            b6.setText("X");
            buttonused[5]=1;
            p1[5] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}            
        }
        else
        {
            turn++;
            b6.setText("O");
            buttonused[5]=1;
            p2[5] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(buttonused[6]==0)
        {
        if(turn%2==0)
        {
            turn++;
            buttonused[6]=1;
            b7.setText("X");
            p1[6] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}      
        }
        else
        {
            turn++;
            b7.setText("O");
            buttonused[6]=1;
            p2[6] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}       
        }
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
         
        if (buttonused[7]==0)
        {
        if(turn%2==0)
        {
            turn++;
            b8.setText("X");
            buttonused[7]=1;
            p1[7] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}            
        }
        else
        {
            turn++;
            b8.setText("O");
            buttonused[7]=1;
            p2[7] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}            
        }
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if (buttonused[8]==0)
        {
        if(turn%2==0)
        {
            turn++;
            b9.setText("X");
            buttonused[8]=1;
            p1[8] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}
        }
        else
        {
            turn++;
            b9.setText("O");
            buttonused[8]=1;
            p2[8] = 1;
            int result1 = p1();
            int result2 = p2();
            if(result1 ==1)
            {tf.setText("player 1 won");}
            else if (result2 == 1)
            {tf.setText("player 2 won");}        
        }
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        turn = 2;
        
        b1.setText(" ");
        b2.setText(" ");
        b3.setText(" ");
        b4.setText(" ");
        b5.setText(" ");
        b6.setText(" ");
        b7.setText(" ");
        b8.setText(" ");
        b9.setText(" ");
        tf.setText(" ");
        
        for (int i=0;i<9;i++)
        {buttonused[i]=0;}

        for (int i=0;i<9;i++)
        {p1[i]=0;}
        for (int i=0;i<9;i++)
        {p2[i]=0;}
    }//GEN-LAST:event_resetActionPerformed

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reset;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
